### ISSUE TITLE
Add apparmor profile

### ISSUE THREAD

**Issue by Obema12** [szorfein/secure-time-sync#1]
You can take it from here https://github.com/Obscurix/Obscurix/blob/master/airootfs/etc/apparmor.d/usr.lib.obscurix.secure-time-sync

**Comment by szorfein** [comment]
Thanks for the example, it's been a very long time since I've used apparmor and no time to test it :(.   
I don't see anything that would allow the use of the socks5-localhost for `--use-tor` or about Tor to see .onion address, What do thing about the commit 968349e, everything is ok ? :)
Just change the path to use /{usr/}bin/secure-time-sync.

**Comment by szorfein** [comment]
Add a profile tested on Debian 11. Thanks.
